In [53]:
# importing the libraries
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
%matplotlib inline


In [9]:
# importing the dataset
data = pd.read_csv('insuranceData.csv')

In [29]:
# Extracting the independent and dependent variables
X = data.iloc[:, :-1].values
Y = data.iloc[:, 4].values

data.head()

age     bmi  children smoker      charges
0   19  27.900         0    yes  16884.92400
1   18  33.770         1     no   1725.55230
2   28  33.000         3     no   4449.46200
3   33  22.705         0     no  21984.47061
4   32  28.880         0     no   3866.85520

In [77]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder = LabelEncoder()
X[:, 2] = labelencoder.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer([('smoker', OneHotEncoder(), [2])], remainder="passthrough")
X = onehotencoder.fit_transform(X)


print(X)

[[0.0 1.0 27.9 0]
 [1.0 0.0 33.77 1]
 [1.0 0.0 33.0 3]
 ...
 [1.0 0.0 36.85 0]
 [1.0 0.0 25.8 0]
 [0.0 1.0 29.07 0]]


In [67]:
X = X[:,1:] #removing the extra column

In [71]:
# Splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.15, random_state=0)